# Unit 3 Sections 14 and 15
- toc: true
- branch: master
- badges: true
- comments: true
- permalink: /jupyter/libraries
- categories: [jupyter,markdown]

# Libraries

* A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. 
* These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.
* A library may also contain documentation, configuration data, message templates, classes, and values, etc.

### Why are libraries important?
* Using Libraries makes Python Programming simpler and convenient for the programmer. 
* One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs. 
* Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

### A few libraries that simplify coding processes:
* **Pillow** allows you to work with images.
* **Tensor Flow** helps with data automation and monitors performance.
* **Matplotlib** allows you to make 2D graphs and plots.

## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

### API’s
* An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used. 
* An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.

In [1]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


## Random Values

* Random number generation (RNG) produces a random number (crazy right?)
    - This means that a procedure with RNG can return different values even if the parameters (inputs) do not change
* CollegeBoard uses <code class="coolCode">RANDOM(A, B)</code>, to return an integer between integers <code class="coolCode">A</code> and <code class="coolCode">B</code>.
    - RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10
    - In Python, this would be <code class="coolCode">random.randint(A, B)</code>, after importing Python's "random" library (<code class="coolCode">import random</code>)
    - JavaScript's works a little differently, with <code class="coolCode">Math.random()</code> returning a value between 0 and 1.
        - To match Python and CollegeBoard, you could make a procedure like [this](https://stackoverflow.com/a/7228322)

#### CollegeBoard Example: What is the possible range of values for *answ3*
![CollegeBoard](https://i.ibb.co/Wt90Hbz/Screen-Shot-2022-12-12-at-7-27-58-AM.png)


#### Convert the following procedure to Python, then determine the range of outputs if n = 5.
<pre>
<font color=white>
PROCEDURE Dice(n)
	sum ← 0
	REPEAT UNTIL n = 0
		sum ← sum + RANDOM(1, 6)
		n ← n - 1
	RETURN sum
</font>
</pre>


In [1]:
def Dice(n):
    sum = 0
    while n != 0:
        sum = sum + random.randint(1, 6)
        n = n - 1
    return sum
    
Dice(5) # Will output a range of 5 to 30

19

1. Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier).

In [2]:
import random

# Generate a list of n random numbers
n = int(input("How many numbers would you like to generate?"))
a = int(input("What is the minimum number you would like to generate?"))
b = int(input("What is the maximum number you would like to generate?"))
numbers = [random.randint(a, b) for _ in range(n)]

# Sort the numbers into even and odd lists
evens = []
odds = []
for number in numbers:
    if number % 2 == 0:
        evens.append(number)
    else:
        odds.append(number)

# Print the even and odd lists
print(evens)
print(odds)

[6, 2, 6, 2, 4]
[5]



2. Using NumPy and only coding in python cell, find the answer to the following questions:
    a. What is the derivative of 2x^5 - 6x^2 + 24x?
    b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

In [3]:
import numpy as np

poly = np.poly1d([2, 0, 0, -6, 24, 0])

# Compute the derivative of the polynomial
derivative = poly.deriv()

# Print the result
print("The derivative of \n" + str(poly) + "\n" + str(derivative))

The derivative of 
   5     2
2 x - 6 x + 24 x
    4
10 x - 12 x + 24



3. Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

In [ ]:
import random

# Create a list of dogs and cats
dogs = ['Dog 1', 'Dog 2', 'Dog 3', 'Dog 4', 'Dog 5', 'Dog 6', 'Dog 7', 'Dog 8', 'Dog 9', 'Dog 10']
cats = ['Cat 1', 'Cat 2', 'Cat 3', 'Cat 4', 'Cat 5', 'Cat 6', 'Cat 7', 'Cat 8', 'Cat 9', 'Cat 10']

# Create a list of tuples, where each tuple contains an animal and a random number
animals = []
for dog in dogs:
    animals.append((dog, random.randint(1, 20)))
for cat in cats:
    animals.append((cat, random.randint(1, 20)))

# Sort the list of tuples based on the random numbers
animals.sort(key=lambda x: x[1])

# Print the animals in the randomized order
for animal in animals:
    print(animal[0])